apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "1"
  creationTimestamp: null
  generation: 1
  name: longhorn-flexvolume-driver
  selfLink: /apis/apps/v1beta2/namespaces/longhorn-system/daemonsets/longhorn-flexvolume-driver
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: longhorn-flexvolume-driver
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: longhorn-flexvolume-driver
      name: longhorn-flexvolume-driver
    spec:
      containers:
      - command:
        - /entrypoint.sh
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: LONGHORN_BACKEND_SVC
          value: longhorn-backend
        image: rancher/longhorn-manager:v0.5.0
        imagePullPolicy: Always
        name: longhorn-flexvolume-driver
        resources: {}
        securityContext:
          privileged: true
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /flexmnt
          name: flexvolume-longhorn-mount
        - mountPath: /binmnt
          name: usr-local-bin-mount
        - mountPath: /host/proc
          name: host-proc-mount
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /var/lib/kubelet/volumeplugins
          type: ""
        name: flexvolume-longhorn-mount
      - hostPath:
          path: /proc
          type: ""
        name: host-proc-mount
      - hostPath:
          path: /usr/local/bin
          type: ""
        name: usr-local-bin-mount
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
