apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: 2019-09-26T09:20:34Z
    generation: 1
    labels:
      app: mongodb
      chart: mongodb-7.2.9
      heritage: Tiller
      release: mongodb
    name: mongodb
    namespace: wekan-project
    resourceVersion: "116127"
    selfLink: /apis/extensions/v1beta1/namespaces/wekan-project/deployments/mongodb
    uid: e4f62380-e03e-11e9-9311-080027c4df3c
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: mongodb
        release: mongodb
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: mongodb
          chart: mongodb-7.2.9
          release: mongodb
      spec:
        containers:
        - env:
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: mongodb-password
                name: mongodb
          - name: MONGODB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: mongodb-root-password
                name: mongodb
          - name: MONGODB_USERNAME
            value: wekan
          - name: MONGODB_SYSTEM_LOG_VERBOSITY
            value: "0"
          - name: MONGODB_DISABLE_SYSTEM_LOG
            value: "no"
          - name: MONGODB_DATABASE
            value: wekan
          - name: MONGODB_ENABLE_IPV6
            value: "no"
          - name: MONGODB_ENABLE_DIRECTORY_PER_DB
            value: "no"
          image: docker.io/bitnami/mongodb:4.0.12-debian-9-r43
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
              - mongo
              - --eval
              - db.adminCommand('ping')
            failureThreshold: 6
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: mongodb
          ports:
          - containerPort: 27017
            name: mongodb
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - mongo
              - --eval
              - db.adminCommand('ping')
            failureThreshold: 6
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources: {}
          securityContext:
            procMount: Default
            runAsNonRoot: true
            runAsUser: 1001
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /bitnami/mongodb
            name: data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext:
          fsGroup: 1001
        terminationGracePeriodSeconds: 30
        volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mongodb
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: 2019-09-26T09:38:32Z
      lastUpdateTime: 2019-09-26T09:38:32Z
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: 2019-09-26T09:38:32Z
      lastUpdateTime: 2019-09-26T09:38:32Z
      message: ReplicaSet "mongodb-5bd7d569c5" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      field.cattle.io/publicEndpoints: '[{"addresses":["192.168.1.181"],"port":32110,"protocol":"TCP","serviceName":"wekan-project:wekan","allNodes":true}]'
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"wekan"},"name":"wekan","namespace":"wekan-project"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"wekan"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"labels":{"app":"wekan"}},"spec":{"containers":[{"env":[{"name":"MONGO_URL","value":"mongodb://wekan:pass@mongodb:27017/wekan"},{"name":"PORT","value":"8080"},{"name":"ROOT_URL","value":"http://wekan.senar.com"}],"image":"quay.io/wekan/wekan:v1.78","name":"wekan","ports":[{"containerPort":8080,"name":"wekan"}]}]}}}}
    creationTimestamp: 2019-09-26T09:38:11Z
    generation: 2
    labels:
      app: wekan
    name: wekan
    namespace: wekan-project
    resourceVersion: "117079"
    selfLink: /apis/extensions/v1beta1/namespaces/wekan-project/deployments/wekan
    uid: 5ab8b01c-e041-11e9-9311-080027c4df3c
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: wekan
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: wekan
      spec:
        containers:
        - env:
          - name: MONGO_URL
            value: mongodb://wekan:pass@mongodb:27017/wekan
          - name: PORT
            value: "8080"
          - name: ROOT_URL
            value: http://wekan.senar.com
          image: quay.io/wekan/wekan:v1.78
          imagePullPolicy: IfNotPresent
          name: wekan
          ports:
          - containerPort: 8080
            name: wekan
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: 2019-09-26T09:40:54Z
      lastUpdateTime: 2019-09-26T09:40:54Z
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: 2019-09-26T09:38:11Z
      lastUpdateTime: 2019-09-26T09:40:54Z
      message: ReplicaSet "wekan-b46f57cc5" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 2
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: 2019-09-26T09:20:34Z
    labels:
      app: mongodb
      chart: mongodb-7.2.9
      heritage: Tiller
      release: mongodb
    name: mongodb
    namespace: wekan-project
    resourceVersion: "113387"
    selfLink: /api/v1/namespaces/wekan-project/services/mongodb
    uid: e4f26360-e03e-11e9-9311-080027c4df3c
  spec:
    clusterIP: 10.43.61.9
    ports:
    - name: mongodb
      port: 27017
      protocol: TCP
      targetPort: mongodb
    selector:
      app: mongodb
      release: mongodb
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      field.cattle.io/publicEndpoints: '[{"addresses":["192.168.1.181"],"port":32110,"protocol":"TCP","serviceName":"wekan-project:wekan","allNodes":true}]'
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"app":"wekan"},"name":"wekan","namespace":"wekan-project","selfLink":"/api/v1/namespaces/wekan-project/services/wekan"},"spec":{"ports":[{"port":8080,"protocol":"TCP","targetPort":8080}],"selector":{"app":"wekan"},"sessionAffinity":"None","type":"NodePort"},"status":{"loadBalancer":{}}}
    creationTimestamp: 2019-09-26T09:42:21Z
    labels:
      app: wekan
    name: wekan
    namespace: wekan-project
    resourceVersion: "117076"
    selfLink: /api/v1/namespaces/wekan-project/services/wekan
    uid: eff7f85b-e041-11e9-9311-080027c4df3c
  spec:
    clusterIP: 10.43.233.172
    externalTrafficPolicy: Cluster
    ports:
    - nodePort: 32110
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: wekan
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
kind: List
