apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      field.cattle.io/publicEndpoints: '[{"addresses":["192.168.1.181"],"port":30488,"protocol":"TCP","serviceName":"xwiki:xwiki-xwiki","allNodes":true},{"addresses":["192.168.1.181"],"port":80,"protocol":"HTTP","serviceName":"xwiki:xwiki-xwiki","ingressName":"xwiki:xwiki-xwiki","path":"/","allNodes":true},{"addresses":["192.168.1.181"],"port":443,"protocol":"HTTPS","serviceName":"xwiki:xwiki-xwiki","ingressName":"xwiki:xwiki-xwiki","path":"/","allNodes":true}]'
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1beta2","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"6","field.cattle.io/publicEndpoints":"[{\"addresses\":[\"192.168.1.180\"],\"port\":80,\"protocol\":\"HTTP\",\"serviceName\":\"xwiki:xwiki-xwiki\",\"ingressName\":\"xwiki:xwiki-xwiki\",\"path\":\"/\",\"allNodes\":true},{\"addresses\":[\"192.168.1.180\"],\"port\":443,\"protocol\":\"HTTPS\",\"serviceName\":\"xwiki:xwiki-xwiki\",\"ingressName\":\"xwiki:xwiki-xwiki\",\"path\":\"/\",\"allNodes\":true}]"},"creationTimestamp":null,"generation":1,"labels":{"app":"xwiki-10.11.8-lts-postgres-tomcat","chart":"xwiki-1.0-SNAPSHOT","version":"10.11.8"},"name":"xwiki-xwiki","namespace":"xwiki","selfLink":"/apis/apps/v1beta2/namespaces/xwiki/deployments/xwiki-xwiki"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"xwiki-xwiki"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"cattle.io/timestamp":"2019-09-25T01:22:07Z","field.cattle.io/ports":"[[{\"containerPort\":8080,\"dnsName\":\"xwiki-xwiki-\",\"name\":\"8080tcp00\",\"protocol\":\"TCP\",\"sourcePort\":0}]]"},"creationTimestamp":null,"labels":{"app":"xwiki-xwiki"}},"spec":{"containers":[{"env":[{"name":"DB_PASSWORD","valueFrom":{"secretKeyRef":{"key":"postgresql-password","name":"xwiki-postgresql","optional":false}}},{"name":"DB_HOST","valueFrom":{"configMapKeyRef":{"key":"DB_HOST","name":"xwiki-xwiki","optional":false}}},{"name":"DB_USER","valueFrom":{"configMapKeyRef":{"key":"DB_USER","name":"xwiki-xwiki","optional":false}}},{"name":"DB_DATABASE","valueFrom":{"configMapKeyRef":{"key":"DB_DATABASE","name":"xwiki-xwiki","optional":false}}}],"image":"xwiki:lts-postgres-tomcat","imagePullPolicy":"IfNotPresent","name":"xwiki","ports":[{"containerPort":8080,"name":"8080tcp00","protocol":"TCP"}],"resources":{"limits":{"cpu":"350m","memory":"1000Mi"},"requests":{"cpu":"150m","memory":"250Mi"}},"securityContext":{"procMount":"Default"},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}]}},"updateStrategy":{"type":"RollingUpdate"},"volumeClaimTemplates":[{"metadata":{"creationTimestamp":null,"name":"data"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"1Gi"}},"volumeMode":"Filesystem"},"status":{"phase":"Pending"}}]},"status":{"replicas":0}}
    creationTimestamp: 2019-09-26T21:15:58Z
    generation: 4
    labels:
      app: xwiki-10.11.8-lts-postgres-tomcat
      chart: xwiki-1.0-SNAPSHOT
      version: 10.11.8
    name: xwiki-xwiki
    namespace: xwiki
    resourceVersion: "119861"
    selfLink: /apis/extensions/v1beta1/namespaces/xwiki/deployments/xwiki-xwiki
    uid: d5898638-e0a2-11e9-9311-080027c4df3c
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: xwiki-xwiki
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          cattle.io/timestamp: 2019-09-25T01:22:07Z
          field.cattle.io/ports: '[[{"containerPort":8080,"dnsName":"xwiki-xwiki-","name":"8080tcp00","protocol":"TCP","sourcePort":0}]]'
        creationTimestamp: null
        labels:
          app: xwiki-xwiki
      spec:
        containers:
        - env:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: postgresql-password
                name: xwiki-postgresql
                optional: false
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                key: DB_HOST
                name: xwiki-xwiki
                optional: false
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                key: DB_USER
                name: xwiki-xwiki
                optional: false
          - name: DB_DATABASE
            valueFrom:
              configMapKeyRef:
                key: DB_DATABASE
                name: xwiki-xwiki
                optional: false
          image: xwiki:lts-postgres-tomcat
          imagePullPolicy: IfNotPresent
          name: xwiki
          ports:
          - containerPort: 8080
            name: 8080tcp00
            protocol: TCP
          resources:
            limits:
              cpu: 350m
              memory: 1000Mi
            requests:
              cpu: 150m
              memory: 250Mi
          securityContext:
            procMount: Default
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: 2019-09-26T21:20:26Z
      lastUpdateTime: 2019-09-26T21:20:26Z
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: 2019-09-26T21:15:58Z
      lastUpdateTime: 2019-09-26T21:20:26Z
      message: ReplicaSet "xwiki-xwiki-648d47dfd" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 4
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: v1
  data:
    DB_DATABASE: xwiki
    DB_HOST: xwiki-postgresql
    DB_USER: xwiki
  kind: ConfigMap
  metadata:
    creationTimestamp: 2019-09-26T21:12:29Z
    labels:
      app: xwiki-xwiki
      chart: xwiki-1.0-SNAPSHOT
      heritage: Tiller
      release: xwiki
    name: xwiki-xwiki
    namespace: xwiki
    resourceVersion: "117883"
    selfLink: /api/v1/namespaces/xwiki/configmaps/xwiki-xwiki
    uid: 58d086b8-e0a2-11e9-9311-080027c4df3c
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: 2019-09-26T21:12:29Z
    labels:
      app: postgresql
      chart: postgresql-5.3.7
      heritage: Tiller
      release: xwiki
    name: xwiki-postgresql
    namespace: xwiki
    resourceVersion: "117895"
    selfLink: /api/v1/namespaces/xwiki/services/xwiki-postgresql
    uid: 58e1c6e9-e0a2-11e9-9311-080027c4df3c
  spec:
    clusterIP: 10.43.125.248
    ports:
    - name: postgresql
      port: 5432
      protocol: TCP
      targetPort: postgresql
    selector:
      app: postgresql
      release: xwiki
      role: master
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: 2019-09-26T21:12:29Z
    labels:
      app: postgresql
      chart: postgresql-5.3.7
      heritage: Tiller
      release: xwiki
    name: xwiki-postgresql-headless
    namespace: xwiki
    resourceVersion: "117888"
    selfLink: /api/v1/namespaces/xwiki/services/xwiki-postgresql-headless
    uid: 58d8d20f-e0a2-11e9-9311-080027c4df3c
  spec:
    clusterIP: None
    ports:
    - name: postgresql
      port: 5432
      protocol: TCP
      targetPort: postgresql
    selector:
      app: postgresql
      release: xwiki
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      field.cattle.io/publicEndpoints: '[{"addresses":["192.168.1.181"],"port":30488,"protocol":"TCP","serviceName":"xwiki:xwiki-xwiki","allNodes":true}]'
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"chart":"xwiki-1.0-SNAPSHOT"},"name":"xwiki-xwiki","namespace":"xwiki","selfLink":"/api/v1/namespaces/xwiki/services/xwiki-xwiki"},"spec":{"ports":[{"name":"http","port":80,"protocol":"TCP","targetPort":8080}],"selector":{"app":"xwiki-xwiki"},"sessionAffinity":"ClientIP","sessionAffinityConfig":{"clientIP":{"timeoutSeconds":10800}},"type":"NodePort"},"status":{"loadBalancer":{}}}
    creationTimestamp: 2019-09-26T21:16:17Z
    labels:
      chart: xwiki-1.0-SNAPSHOT
    name: xwiki-xwiki
    namespace: xwiki
    resourceVersion: "118610"
    selfLink: /api/v1/namespaces/xwiki/services/xwiki-xwiki
    uid: e13d3c5a-e0a2-11e9-9311-080027c4df3c
  spec:
    clusterIP: 10.43.223.210
    externalTrafficPolicy: Cluster
    ports:
    - name: http
      nodePort: 30488
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: xwiki-xwiki
    sessionAffinity: ClientIP
    sessionAffinityConfig:
      clientIP:
        timeoutSeconds: 10800
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: apps/v1beta1
  kind: StatefulSet
  metadata:
    creationTimestamp: 2019-09-26T21:12:29Z
    generation: 1
    labels:
      app: postgresql
      chart: postgresql-5.3.7
      heritage: Tiller
      release: xwiki
    name: xwiki-postgresql
    namespace: xwiki
    resourceVersion: "118214"
    selfLink: /apis/apps/v1beta1/namespaces/xwiki/statefulsets/xwiki-postgresql
    uid: 58f39592-e0a2-11e9-9311-080027c4df3c
  spec:
    podManagementPolicy: OrderedReady
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: postgresql
        release: xwiki
        role: master
    serviceName: xwiki-postgresql-headless
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: postgresql
          chart: postgresql-5.3.7
          heritage: Tiller
          release: xwiki
          role: master
        name: xwiki-postgresql
      spec:
        containers:
        - env:
          - name: BITNAMI_DEBUG
            value: "false"
          - name: POSTGRESQL_PORT_NUMBER
            value: "5432"
          - name: PGDATA
            value: /bitnami/postgresql/data
          - name: POSTGRES_USER
            value: xwiki
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: postgresql-password
                name: xwiki-postgresql
          - name: POSTGRES_DB
            value: xwiki
          image: docker.io/bitnami/postgresql:11.3.0-debian-9-r38
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
              - sh
              - -c
              - exec pg_isready -U "xwiki" -d "xwiki" -h 127.0.0.1 -p 5432
            failureThreshold: 6
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: xwiki-postgresql
          ports:
          - containerPort: 5432
            name: postgresql
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - sh
              - -c
              - |
                pg_isready -U "xwiki" -d "xwiki" -h 127.0.0.1 -p 5432
                [ -f /opt/bitnami/postgresql/tmp/.initialized ]
            failureThreshold: 6
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
          securityContext:
            procMount: Default
            runAsUser: 1001
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /bitnami/postgresql
            name: data
        dnsPolicy: ClusterFirst
        initContainers:
        - command:
          - sh
          - -c
          - |
            mkdir -p /bitnami/postgresql/data
            chmod 700 /bitnami/postgresql/data
            find /bitnami/postgresql -mindepth 1 -maxdepth 1 -not -name ".snapshot" | \
              xargs chown -R 1001:1001
          image: docker.io/bitnami/minideb:latest
          imagePullPolicy: Always
          name: init-chmod-data
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
          securityContext:
            procMount: Default
            runAsUser: 0
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /bitnami/postgresql
            name: data
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext:
          fsGroup: 1001
        terminationGracePeriodSeconds: 30
    updateStrategy:
      type: RollingUpdate
    volumeClaimTemplates:
    - metadata:
        creationTimestamp: null
        name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 8Gi
        volumeMode: Filesystem
      status:
        phase: Pending
  status:
    collisionCount: 0
    currentReplicas: 1
    currentRevision: xwiki-postgresql-685b88c89f
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updateRevision: xwiki-postgresql-685b88c89f
    updatedReplicas: 1
kind: List
