apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    field.cattle.io/publicEndpoints: '[{"addresses":["192.168.1.161"],"port":32000,"protocol":"TCP","serviceName":"devops-tools:nexus-service","allNodes":true}]'
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"name":"nexus","namespace":"devops-tools"},"spec":{"replicas":1,"template":{"metadata":{"labels":{"app":"nexus-server"}},"spec":{"containers":[{"image":"sonatype/nexus3:latest","name":"nexus","ports":[{"containerPort":8081}],"resources":{"limits":{"cpu":"1000m","memory":"4Gi"},"requests":{"cpu":"500m","memory":"2Gi"}},"volumeMounts":[{"mountPath":"/nexus-data","name":"nexus-data"}]}],"volumes":[{"claimName":"nexus-data","name":"nexus-data","persistentVolumeClaim":null}]}}}}'
  creationTimestamp: null
  generation: 1
  labels:
    app: nexus-server
  name: nexus
  selfLink: /apis/apps/v1beta2/namespaces/devops-tools/deployments/nexus
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      app: nexus-server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2019-08-06T22:44:48Z"
        field.cattle.io/ports: '[[{"containerPort":8081,"dnsName":"nexus-","name":"8081tcp00","protocol":"TCP","sourcePort":0}]]'
      creationTimestamp: null
      labels:
        app: nexus-server
    spec:
      containers:
      - image: sonatype/nexus3:latest
        imagePullPolicy: Always
        name: nexus
        ports:
        - containerPort: 8081
          name: 8081tcp00
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 2Gi
        securityContext:
          capabilities: {}
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /nexus-data
          name: nexus-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nexus-data
        persistentVolumeClaim:
          claimName: nexus-data
status: {}
